### PR TITLE
Aptfile :repo: line add custom repositories

### PR DESCRIPTION
**Pull request by drnic**
This PR adds the ability for a user to add custom repositories. It uses the same syntax as the https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt

```
:repo:deb http://cz.archive.ubuntu.com/ubuntu artful main universe
```

Note: I'm unsure how to support custom repositories that have their own key, since `apt-key add` must be run as root. Any suggestions welcome.

For example, I cannot use http://apt.starkandwayne.com/ since it has its own public key. That is, the following line will fail:

```
:repo:deb http://apt.starkandwayne.com stable main
```

The buildpack error will be:
```
   W: GPG error: http://apt.starkandwayne.com stable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E8A5EA6A535EAEC4
```

Note to self from Slack:

screen shot 2017-10-24 at 6 30 16 am

### CODE REVIEW

**Comment by drnic** [comment]
Still working on this; but discovered that even without supporting custom keys a user can include `deb [trusted=yes]` to ignore keys:

```
:repo:deb [trusted=yes] http://apt.starkandwayne.com stable main
spruce
```

Add a little endpoint to the `app.rb` to check that `spruce` CLI was installed:

```
$ curl -k https://simple-apt.10-58-111-49.sslip.io/spruce
Spruce: spruce - Version 1.12.1
```

**Comment by drnic** [comment]
Woohoo! Custom keys being installed:

```
Staging package for app simple-apt in org system / space dev as admin...
   -----> Running go build supply
   -----> Apt Buildpack version 0.0.2
   -----> Updating apt cache
   Installing custom repository key from https://raw.githubusercontent.com/starkandwayne/homebrew-cf/master/public.key
   gpg: key 535EAEC4: public key "Stark & Wayne Bot (Created by CI) <drnic+bot@starkandwayne.com>" imported
   gpg: Total number processed: 1
   gpg:               imported: 1  (RSA: 1)
   -----> Downloading apt packages
   -----> Installing apt packages
   -----> Ruby Buildpack version 1.7.3
   -----> Supplying Ruby
```

**Comment by drnic** [comment]
Ok, integration + unit tests are passing.

**Comment by sclevine** [comment]
Thanks @drnic, we'll get this in for the next release :)

**Comment by drnic** [comment]
Demo app that uses this branch https://github.com/cloudfoundry-community/bosh-cli-web-demo for a blog post I'll write after next apt-buildpack release 👍

**Comment by dgodd** [comment]
@drnic We have merged this PR. In doing so we decided to change Aptfile to Aptfile.yml and separate packages/keys/repos into three separate attributes.

**Comment by drnic** [comment]
Ah you have `develop` branch. I'll submit PRs to it in future.

**Pull request merged**
